language: clojure
lein: lein2
jdk:
  - openjdk7
services:
  - mongodb
env: TEST_DB=mongo
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script:
  - "lein2 cljx once"
  - "lein2 with-profile release cljsbuild once"
  
script: "lein2 test"
